version: '3.8'

services:

  rust-server:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - redis_db
      - postgres

    networks:
      - App_Network

    volumes:
      - rust-server-data:/usr/src/redis-curd/data


  postgres:
    image: postgres:latest

    restart: always

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AppDB

    ports:
      - "7001:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - App_Network




  redis_db:

    image: redis/redis-stack:latest

    restart: always

#    environment:
#     REDIS_ARGS: "--requirepass root"

    ports:
      - "7002:6379"
      - "7003:8001"

    volumes:
      - redis-data:/data

    networks:
      - App_Network


networks:
  App_Network:
    ipam:
      config:
        - subnet: 172.1.1.0/24

volumes:
  rust-server-data:
  postgres-data:
  redis-data: